Objektno/Models/ReceiptViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using KonobApp.Model.Models;

namespace Objektno.Models
{
    public class ReceiptViewModel
    {
        public List<ArticleModel> articlesInCaffe;
        public IDictionary<int, string> categories = new Dictionary<int,string>();
        public ReceiptModel receipt = new ReceiptModel();


        internal ReceiptViewModel(int id)
        {
            var caffeRepository = DAL.Repositories.CaffeRepository.GetInstance();

            articlesInCaffe = caffeRepository.ListAvailableArticlesInCaffe(id).ToList();
            var aviableCategoriesInCaffe = articlesInCaffe.Select(t => t.IDCategory).Distinct().ToList();

            using (DAL.Facade facade = new DAL.Facade())
            {
                var temp = facade.FetchAll<CategoryModel>();
                foreach(var value in temp)
                {
                    if (aviableCategoriesInCaffe.Contains(value.IDCategory))
                    {
                        categories.Add(new KeyValuePair<int, string>(value.IDCategory, value.Name));
                    }
                }
            }

            receipt.Articles= new List<ArticleModel>();
            receipt.ArtRec = new List<ArticleReceiptModel>();
        }

        /// <summary>
        /// Late night hotfix
        /// </summary>
        /// <param name="receipt"></param>
        internal void ProcessRecieptBeforeSending(ref ReceiptModel receipt)
        {
            receipt.Date = DateTime.Now;
            receipt.ArtRec = new List<ArticleReceiptModel>();
            receipt.Discount = 0;
            receipt.IDPaymentMethod = 1;
            receipt.IDUser = 1;
            receipt.IDWaiter = 1;
            receipt.TotalCost = (float)receipt.SetTotal();
        }

        internal void addArticle(int iDArticle)
        {
            var article = articlesInCaffe.Where(t => t.IDArticle == iDArticle).First();

            receipt.Articles.Add(article);
        }
    }
}

Objektno/Controllers/ReceiptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Objektno.Models;

namespace Objektno.Controllers
{
    public class ReceiptController : Controller
    {
        private  static ReceiptViewModel viewModel;
        public ActionResult Create(int? IDCaffe)
        {
            viewModel = new ReceiptViewModel((int)IDCaffe);

            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Create(int? IDArticle, int? quantity)
        {
            viewModel.addArticle((int)IDArticle);
            return View(viewModel);
        }

        public ActionResult SendReceipt()
        {
            viewModel.ProcessRecieptBeforeSending(ref viewModel.receipt);

            Notifications.NotificationService.SendReciept(viewModel.receipt);

            return View();
        }
    }
}

Objektno/Views/Receipt/Create.cshtml
@model Objektno.Models.ReceiptViewModel
@{
    ViewBag.Title = "Create";
}
<div class="container">
    <div class="col-lg-8 col-md-auto">
        @for (int i = 0; i < @Model.categories.Count; i++)
        {
            @Html.Raw("<div class=\"container\" id=\"categoryContainer\">")
            @Html.Raw("<h2>")
            @Model.categories.ElementAt(i).Value
            @Html.Raw("</h2>")
            var path = "~/Images/" + Model.categories.ElementAt(i).Key + ".jpg";
            <img src="@Url.Content(path)" width="700" height="250" id="picture" />
            <br />
            foreach (var article in @Model.articlesInCaffe)
            {
                if (Model.categories.ElementAt(i).Key == article.IDCategory)
                {
                    var routeValues = new RouteValueDictionary();
                    routeValues.Add("IDArticle", article.IDArticle);
                    //routeValues.Add("quantity",);

                    @Html.Raw("<p id=articleNameText><b>")
                    @Html.Raw(article.Name)

                    using (Html.BeginForm(routeValues))
                    {
                        @*@Html.TextBox("Količina","quantity");*@
                        <input type="submit" id="addButton" value="Dodaj">
                    }

                    @Html.Raw("</p></b>")

                    @Html.Raw("<p id=articlePriceText><b>")
                    @Html.Raw(article.Price + " kn")
                    @Html.Raw("</p></b>")

                    //inb4 LOL
                    @Html.Raw("<br/>")
                    @Html.Raw("<br/>")
                    @Html.Raw("<br/>")
                    @Html.Raw("<br/>")

                }
            }
            @Html.Raw("</div>")
        }
    </div>
</div>

<div class="flex-container" id="receiptContainer">
    <ul>
        @foreach (var article in Model.receipt.Articles)
        {
            <li>
                @article.Name
            </li>
        }
    </ul>
    @Html.ActionLink("Naruči", "SendReceipt", "Receipt")
</div>

<style>
    #categoryContainer {
        margin: 100px;
        margin-top: 50px;
        padding: 10px;
    }

    #articleNameText {
        font-size: medium;
        margin: 15px;
        color: black;
        float: left;
        text-align: left;
    }

    #articlePriceText {
        margin: 5px;
        font-size: medium;
        position: absolute;
        right: 80px;
        /*float: right;
        text-align: end;*/
        /*margin-right:80px;*/
    }

    #addButton {
        padding: 2px;
        position: absolute;
        right: 0px;
        background-color: darkorange;
        font-size: medium;
    }

    #picture {
        margin: 20px;
    }

    #receiptContainer {
        background-color: cornflowerblue;
        width: auto;
        height: auto;
        margin: 10px;
        position:absolute;
        right:0px;
        top:80px;
    }
</style>